CONNECT system/bdadmin

CREATE USER practica8 IDENTIFIED BY p8;
GRANT CONNECT, RESOURCE TO practica8;

CONNECT practica8/p8

CREATE TABLE ARTICULO
(
    codigo VARCHAR2(6) CONSTRAINT art_cod_pk PRIMARY KEY,
    stock  NUMBER(3) DEFAULT 0 
                     CONSTRAINT art_sto_nn NOT NULL 
                     CONSTRAINT art_sto_ch CHECK (stock >= 0)
);

INSERT INTO ARTICULO VALUES ('ART1',0);
INSERT INTO ARTICULO VALUES ('ART2',7);
INSERT INTO ARTICULO VALUES ('ART3',4);
INSERT INTO ARTICULO VALUES ('ART4',12);

COMMIT;

SHOW USER
SELECT * FROM ARTICULO;
